apiVersion: logging.jiocloud.com/v1alpha1
kind: LogManagement
metadata:
  name: log-manager
spec:
  fluentbit-logfile: /var/log/fluentbits.log
  include-k8s-metadata: true
  elasticsearch: true
  kibana: true
  namespace: logging
  es-kib-version: "6.4.2"
  inputs:
    - deployment-name: sample-pod
      tag: kube
      parser: apache
      index-pattern: sample-pod
  parsers:
    - name: apache
      regex: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<log_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>.*)")?$'
  outputs:
    - type: stdout
  