apiVersion: logging.jiocloud.com/v1alpha1
kind: LogManagement
metadata:
  name: log-manager
  namespace: logging
spec:
  fluentbit-logfile: /var/log/fluentbit.log
  include-k8s-metadata: true
  elasticsearch-spec:
    required: true
    host: http://sdfdsf.com/sad
    port: "9200"
  kibana: true
  es-kib-version: "6.4.2"
  watch:
    - namespace: default
      parsers:
        - name: apache
        - name: apache_error
      outputs:
        - type: elasticsearch
          index-pattern: sit
        - type: stdout
  parsers:
    - name: apache
      regex: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<log_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>.*)")?$'
    - name: apache_error
      regex: '^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$'
    - name: all
      regex: '.*'
  