apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-operator
  namespace: logging

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-operator
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - daemonsets
  - deployments
  - logmanagements
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - namespaces
  verbs: ["get", "watch", "list", "update", "delete", "create"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-operator
subjects:
- kind: ServiceAccount
  name: logging-operator
  namespace: logging
roleRef:
  kind: ClusterRole
  name: logging-operator
  apiGroup: rbac.authorization.k8s.io
