kind: Service
apiVersion: v1
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    run: fluentd
  ports:
  - protocol: TCP
    port: 8777
    targetPort: 8777

---

kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
apiVersion: v1
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush          1
        Daemon         Off
        Log_Level      info
        Log_File       /var/log/fluent_bit.log
        Parsers_File   parsers.conf
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_Port      2020

    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/sample*
        Parser         json_parser

    [FILTER]
        Name                parser
        Match               kube.*
        Key_Name            log
        Parser              apache2

    [FILTER]
        Name                parser
        Match               kube.*
        Key_Name            log
        Parser              apache_error

    [FILTER]
        Name                kubernetes
        Match               kube.*
        K8S-Logging.Parser  On
        Merge_Log           On

    [OUTPUT]
        Name            forward
        Match           *
        Host            ${FLUENTD_SERVICE_HOST}
        Port            ${FLUENTD_SERVICE_PORT}

  parsers.conf: |-
    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<log_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>.*)")?$

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name        json_parser
        Format      json
        Decode_Field_As    escaped     log

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.14.6
        ports:
          - containerPort: 2020
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
