apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 8777
      bind 0.0.0.0
    </source>

    <filter **>
      @type elasticsearch_timestamp_check
    </filter>
    
    <match kube**>
      @type copy
      <store>
        @type elasticsearch
        host "#{ENV['ES_HOST']}"
        port "#{ENV['ES_PORT']}"
        flush_interval 1s
        logstash_format true
        logstash_prefix sample-pod
      </store>
    </match>

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    matchLabels:
      run: fluentd
  template:
    metadata:
      labels:
        run: fluentd
    spec:
      containers:
      - name: fluentd
        image: jc-fluentd:v1
        env:
        - name: FLUENTD_CONF
          value: fluent.conf
        - name: ES_HOST
          value: $(ELASTICSEARCH_SERVICE_HOST)
        - name: ES_PORT
          value: $(ELASTICSEARCH_SERVICE_PORT)
        ports:
        - containerPort: 8777
        volumeMounts:
        - name: varlog
          mountPath: /fluentd/log
        - name: config-volume
          mountPath: /fluentd/etc
      volumes:
      - name: varlog
        emptyDir: {}
      - name: config-volume
        configMap:
          name: fluentd-config
